fix port

diff --git a/Jenkinsfile-1 b/Jenkinsfile-1
--- a/Jenkinsfile-1
+++ b/Jenkinsfile-1
@@ -5,30 +5,44 @@ pipeline {
     }
     environment {
         MAVEN_OPTS = "-Dmaven.repo.local=${env.JENKINS_HOME}/.m2/repository"
-        // Use environment-specific database URL
-        MYSQL_HOST = 'mysql-container'  // Will be the Docker container name
+        MYSQL_PORT = ''  // Will be set dynamically
     }
     stages {
         stage('Start MySQL') {
             steps {
                 script {
+                    // Run MySQL with random port
                     sh '''
+                        docker stop mysql-container || true
+                        docker rm mysql-container || true
+                        
+                        # Run with random port
                         docker run --name mysql-container \
                             -e MYSQL_ALLOW_EMPTY_PASSWORD=yes \
                             -e MYSQL_DATABASE=studentdb \
-                            -p 3306:3306 \
+                            -P \
                             -d mysql:8
-                        # Wait for MySQL to be ready
-                        sleep 30
+                        
+                        sleep 15
+                        
+                        # Get the actual port that was assigned
+                        MYSQL_PORT=$(docker port mysql-container 3306 | cut -d: -f2)
+                        echo "MYSQL_PORT=${MYSQL_PORT}" > mysql_port.txt
                     '''
                 }
             }
         }
         stage('Scan') {
             steps {
-                withSonarQubeEnv('sq1') {
-                    sh 'chmod +x mvnw'
-                    sh './mvnw clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.0.2155:sonar'
+                script {
+                    // Read the port from file
+                    def portProps = readProperties file: 'mysql_port.txt'
+                    def mysqlPort = portProps['MYSQL_PORT']
+                    
+                    withSonarQubeEnv('sq1') {
+                        sh 'chmod +x mvnw'
+                        sh "./mvnw clean verify -Dspring.datasource.url=jdbc:mysql://localhost:${mysqlPort}/studentdb?createDatabaseIfNotExist=true org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.0.2155:sonar"
+                    }
                 }
             }
         }
@@ -42,9 +56,15 @@ pipeline {
     }
     post {
         always {
-            // Clean up MySQL container
-            sh 'docker stop mysql-container || true'
-            sh 'docker rm mysql-container || true'
+            script {
+                try {
+                    sh 'docker stop mysql-container || true'
+                    sh 'docker rm mysql-container || true'
+                    sh 'rm -f mysql_port.txt'
+                } catch (Exception e) {
+                    echo "Could not clean up"
+                }
+            }
             archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true
             junit '**/target/surefire-reports/*.xml'
         }
